### ISSUE TITLE
Toggle stops with backtick

### ISSUE THREAD

**Issue by slyy** [atom/toggle-quotes#51]
I have added backtick alongside single quote & double-quote (ha! Javascript devs ;))

When I toggle now, it goes " => ' => ` then it stops and does not toggle anymore.

**Comment by slyy** [comment]
Mentioned in https://github.com/atom/toggle-quotes/issues/35

**Comment by mattyclarkson** [comment]
I have exactly the same issue, but #35 says that it is fixed.

**Comment by Ben3eeE** [comment]
@mattyclarkson From what I understand this happens when the quote character you toggle to is not recognized by the language.

https://github.com/atom/toggle-quotes/pull/45 looks like it's aiming to fix this.

**Comment by pdxwolfy** [comment]
Broken for me in JavaScript - it stops cycling at backticks.

**Comment by pdxwolfy** [comment]
This works under 1.1.3 now; thanks!

**Comment by Ben3eeE** [comment]
This was fixed by @savetheclocktower

**Comment by softwarecreations** [comment]
This issue is not fixed.
The fact that we can now define custom ticks by filetype is a _slight_ help but not really.
For example PHP files can embed <script> tags then have JavaScript embedded.
The same goes for JSX.
In JSX, for a JSX element's properties you can only use single or double quotes. But in JavaScript you can use single, double or backticks.

**Comment by savetheclocktower** [comment]
TextMate solved this issue by having several different commands bound to the same shortcut, each one bound to a different scope context. Then each language bundle could write its own toggling logic, even applying the proper escape rules during the cycle. The downside was that the bundle maintainer was responsible for writing that command.

What you're describing is desirable, but I don't know of an easy way to get there. One of the major things on my Atom wishlist is to be able to bind commands to very specific scopes, like TextMate can (e.g., a command that will only run inside of a block comment, or a JavaScript template string, or whatever). With that feature, the burden of those complex edge cases falls on the language bundle, where (in my opinion) it ought to be.

Without it, the burden falls on a single package that must respond to all “Toggle Quotes“ commands and has to know about all those cases itself. To do this would require tight coupling to other packages. It would mean that an innocuous change in the `language-php` grammar could break quote-toggling because it's no longer producing the descriptor that this package would expect. And it would mean that a new language wouldn't get any quote toggling until someone updated this package with the necessary logic.

(Caveat: these are just my recollections of code I haven't touched in a couple of years, and I'd be thrilled to learn that there was an easier way to pull this off that I hadn't thought of.)
